from typing import List, Dict

CATEGORIES = [
    {"id": "cleaning", "name": "Home Cleaning", "icon": "🧹", "description": "Professional cleaning services", "service_count": 8},
    {"id": "salon", "name": "Salon & Spa", "icon": "💆", "description": "Beauty and wellness at home", "service_count": 7},
    {"id": "appliance", "name": "Appliance Repair", "icon": "🔧", "description": "Fix your home appliances", "service_count": 6},
    {"id": "plumbing", "name": "Plumbing", "icon": "🚿", "description": "Expert plumbing solutions", "service_count": 5},
    {"id": "electrical", "name": "Electrician", "icon": "⚡", "description": "Certified electrical services", "service_count": 5},
    {"id": "painting", "name": "Painting", "icon": "🎨", "description": "Home painting services", "service_count": 4},
    {"id": "pest", "name": "Pest Control", "icon": "🐛", "description": "Pest & termite control", "service_count": 4},
    {"id": "carpentry", "name": "Carpentry", "icon": "🪚", "description": "Furniture & carpentry work", "service_count": 4},
]

SERVICES = [
    {
        "id": 1,
        "name": "Full Home Deep Cleaning",
        "category_id": "cleaning",
        "category": "Cleaning",
        "description": "Our expert team does thorough cleaning of your entire home including kitchen, bathrooms, and all rooms. We use eco-friendly products and advanced equipment.",
        "rating": 4.9,
        "reviews_count": 12500,
        "price": 79,
        "original_price": 99,
        "duration": "4-5 hours",
        "image": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=400&fit=crop",
        "badge": "Bestseller",
        "includes": ["Kitchen cleaning", "Bathroom scrubbing", "Floor mopping", "Window wiping", "Furniture dusting"],
        "professionals_count": 450,
    },
    {
        "id": 2,
        "name": "Bathroom Deep Cleaning",
        "category_id": "cleaning",
        "category": "Cleaning",
        "description": "Complete bathroom sanitization including tiles, fixtures, and hard-to-reach areas. Removes tough stains and limescale.",
        "rating": 4.8,
        "reviews_count": 8700,
        "price": 35,
        "original_price": 45,
        "duration": "1.5 hours",
        "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Tile scrubbing", "Toilet sanitization", "Shower cleaning", "Mirror polishing"],
        "professionals_count": 320,
    },
    {
        "id": 3,
        "name": "Kitchen Deep Cleaning",
        "category_id": "cleaning",
        "category": "Cleaning",
        "description": "Professional kitchen cleaning covering chimney, stove, countertops, and cabinets. Make your kitchen sparkle!",
        "rating": 4.7,
        "reviews_count": 6400,
        "price": 45,
        "original_price": 60,
        "duration": "2-3 hours",
        "image": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop",
        "badge": "Popular",
        "includes": ["Chimney cleaning", "Stove cleaning", "Cabinet wipe-down", "Countertop polish"],
        "professionals_count": 280,
    },
    {
        "id": 4,
        "name": "Sofa & Carpet Cleaning",
        "category_id": "cleaning",
        "category": "Cleaning",
        "description": "Deep steam cleaning for sofas, carpets and upholstery. Removes stains, allergens and odors effectively.",
        "rating": 4.8,
        "reviews_count": 5200,
        "price": 59,
        "original_price": None,
        "duration": "2-3 hours",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Steam cleaning", "Stain removal", "Deodorizing", "Dry cleaning"],
        "professionals_count": 210,
    },
    {
        "id": 5,
        "name": "AC Service & Repair",
        "category_id": "appliance",
        "category": "Appliance Repair",
        "description": "Complete AC servicing including filter cleaning, gas check, and performance optimization. Keeps your AC running efficiently.",
        "rating": 4.8,
        "reviews_count": 9800,
        "price": 49,
        "original_price": 69,
        "duration": "1-2 hours",
        "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=400&fit=crop",
        "badge": "Most Booked",
        "includes": ["Filter cleaning", "Gas level check", "Coil cleaning", "Performance test"],
        "professionals_count": 380,
    },
    {
        "id": 6,
        "name": "Washing Machine Repair",
        "category_id": "appliance",
        "category": "Appliance Repair",
        "description": "Expert diagnosis and repair for all brands of washing machines — front load, top load, and semi-automatic.",
        "rating": 4.7,
        "reviews_count": 4300,
        "price": 39,
        "original_price": None,
        "duration": "1-2 hours",
        "image": "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Diagnosis", "Part replacement", "Test wash", "Warranty on repair"],
        "professionals_count": 190,
    },
    {
        "id": 7,
        "name": "Refrigerator Repair",
        "category_id": "appliance",
        "category": "Appliance Repair",
        "description": "Repair all types of refrigerators, from cooling issues to compressor problems. All brands covered.",
        "rating": 4.6,
        "reviews_count": 3100,
        "price": 45,
        "original_price": 55,
        "duration": "1-2 hours",
        "image": "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Diagnosis", "Cooling check", "Gas refill if needed", "90-day warranty"],
        "professionals_count": 160,
    },
    {
        "id": 8,
        "name": "Classic Facial & Cleanup",
        "category_id": "salon",
        "category": "Salon & Spa",
        "description": "Rejuvenating facial treatment at home. Includes cleansing, exfoliation, face massage, and a hydrating mask.",
        "rating": 4.9,
        "reviews_count": 15600,
        "price": 39,
        "original_price": 55,
        "duration": "45 mins",
        "image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop",
        "badge": "Top Rated",
        "includes": ["Cleansing", "Exfoliation", "Face massage", "Hydrating mask", "Moisturizer"],
        "professionals_count": 520,
    },
    {
        "id": 9,
        "name": "Full Body Massage",
        "category_id": "salon",
        "category": "Salon & Spa",
        "description": "Relaxing full body massage by certified therapists at your doorstep. Choose from Swedish, deep tissue, or aromatherapy.",
        "rating": 4.9,
        "reviews_count": 9200,
        "price": 89,
        "original_price": 120,
        "duration": "60 mins",
        "image": "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop",
        "badge": "Popular",
        "includes": ["Full body massage", "Aromatherapy oil", "Hot towel compress", "Relaxation music"],
        "professionals_count": 340,
    },
    {
        "id": 10,
        "name": "Haircut & Styling (Women)",
        "category_id": "salon",
        "category": "Salon & Spa",
        "description": "Professional haircut, wash, blow-dry, and styling by expert stylists at home. Includes hair consultation.",
        "rating": 4.8,
        "reviews_count": 11200,
        "price": 49,
        "original_price": 65,
        "duration": "1 hour",
        "image": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop",
        "badge": "Bestseller",
        "includes": ["Hair wash", "Haircut", "Blow dry", "Styling"],
        "professionals_count": 460,
    },
    {
        "id": 11,
        "name": "Plumbing - Leak Repair",
        "category_id": "plumbing",
        "category": "Plumbing",
        "description": "Fast and reliable leak detection and repair for pipes, taps, and fixtures. No mess, quick fix.",
        "rating": 4.7,
        "reviews_count": 6700,
        "price": 29,
        "original_price": None,
        "duration": "Per hour",
        "image": "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Leak detection", "Pipe repair", "Tap repair", "Sealant application"],
        "professionals_count": 250,
    },
    {
        "id": 12,
        "name": "Bathroom Tap & Fitting",
        "category_id": "plumbing",
        "category": "Plumbing",
        "description": "Installation and replacement of bathroom taps, shower heads, and fittings. Quick and clean work.",
        "rating": 4.6,
        "reviews_count": 3400,
        "price": 35,
        "original_price": 45,
        "duration": "1-2 hours",
        "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Tap installation", "Shower fitting", "Leak testing"],
        "professionals_count": 180,
    },
    {
        "id": 13,
        "name": "Electrician - Multiple Jobs",
        "category_id": "electrical",
        "category": "Electrician",
        "description": "Certified electricians for wiring, switchboard repair, fan installation, and all electrical work.",
        "rating": 4.6,
        "reviews_count": 4500,
        "price": 29,
        "original_price": None,
        "duration": "Per hour",
        "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Wiring work", "Switchboard repair", "Fan installation", "Light fitting"],
        "professionals_count": 290,
    },
    {
        "id": 14,
        "name": "Fan & Light Installation",
        "category_id": "electrical",
        "category": "Electrician",
        "description": "Safe installation of ceiling fans, LED lights, and fixtures. Includes wiring and testing.",
        "rating": 4.7,
        "reviews_count": 3800,
        "price": 25,
        "original_price": 35,
        "duration": "30-60 mins",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
        "badge": "Quick Fix",
        "includes": ["Fan installation", "Light fitting", "Wiring", "Safety check"],
        "professionals_count": 220,
    },
    {
        "id": 15,
        "name": "Interior Home Painting",
        "category_id": "painting",
        "category": "Painting",
        "description": "Professional interior painting with premium quality paints. Neat, quick and clean with zero mess.",
        "rating": 4.8,
        "reviews_count": 5600,
        "price": 199,
        "original_price": 249,
        "duration": "1-3 days",
        "image": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&h=400&fit=crop",
        "badge": "Premium",
        "includes": ["Wall prep", "Primer coat", "2 paint coats", "Touch-up", "Clean up"],
        "professionals_count": 170,
    },
    {
        "id": 16,
        "name": "Cockroach & Ant Control",
        "category_id": "pest",
        "category": "Pest Control",
        "description": "Effective pest control treatment for cockroaches, ants, and common household pests. Safe for children and pets.",
        "rating": 4.7,
        "reviews_count": 7200,
        "price": 49,
        "original_price": 69,
        "duration": "1-2 hours",
        "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=400&fit=crop",
        "badge": "Popular",
        "includes": ["Gel treatment", "Spray treatment", "30-day guarantee"],
        "professionals_count": 200,
    },
    {
        "id": 17,
        "name": "Furniture Assembly",
        "category_id": "carpentry",
        "category": "Carpentry",
        "description": "Assemble flat-pack furniture (IKEA, Pepperfry, Urban Ladder, etc.) quickly and correctly.",
        "rating": 4.7,
        "reviews_count": 4100,
        "price": 35,
        "original_price": None,
        "duration": "Per piece",
        "image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop",
        "badge": None,
        "includes": ["Assembly", "Tightening & adjustment", "Safety check"],
        "professionals_count": 190,
    },
]

REVIEWS = [
    {"id": 1, "service_id": 1, "user_name": "Priya Sharma", "user_avatar": "https://i.pravatar.cc/150?img=1", "rating": 5, "comment": "Absolutely amazing service! The team was professional, on time, and my house looks brand new. Will definitely book again.", "date": "2024-02-15"},
    {"id": 2, "service_id": 1, "user_name": "Rohit Verma", "user_avatar": "https://i.pravatar.cc/150?img=2", "rating": 5, "comment": "Exceeded my expectations! Every corner was spotless. The professionals were courteous and efficient.", "date": "2024-02-10"},
    {"id": 3, "service_id": 1, "user_name": "Anita Desai", "user_avatar": "https://i.pravatar.cc/150?img=5", "rating": 4, "comment": "Great service overall. Minor issue with timing but the quality was top-notch.", "date": "2024-01-28"},
    {"id": 4, "service_id": 5, "user_name": "Vikram Kumar", "user_avatar": "https://i.pravatar.cc/150?img=3", "rating": 5, "comment": "AC is running like new! The technician explained everything clearly and was very professional.", "date": "2024-02-18"},
    {"id": 5, "service_id": 5, "user_name": "Neha Gupta", "user_avatar": "https://i.pravatar.cc/150?img=6", "rating": 5, "comment": "Very satisfied! The technician came on time, serviced the AC thoroughly. Worth every rupee.", "date": "2024-01-20"},
    {"id": 6, "service_id": 8, "user_name": "Sunita Rao", "user_avatar": "https://i.pravatar.cc/150?img=7", "rating": 5, "comment": "Brilliant facial! The beautician was skilled and used quality products. My skin feels amazing!", "date": "2024-02-12"},
    {"id": 7, "service_id": 9, "user_name": "Kavitha M", "user_avatar": "https://i.pravatar.cc/150?img=8", "rating": 5, "comment": "Best massage ever! The therapist was professional and the oils smelled divine. Totally relaxed!", "date": "2024-02-05"},
    {"id": 8, "service_id": 2, "user_name": "Arun Patel", "user_avatar": "https://i.pravatar.cc/150?img=4", "rating": 4, "comment": "Bathroom looks brand new! Good job, though took a bit longer than expected.", "date": "2024-01-30"},
    {"id": 9, "service_id": 10, "user_name": "Meera Joshi", "user_avatar": "https://i.pravatar.cc/150?img=9", "rating": 5, "comment": "Loved the haircut! The stylist was talented and understood exactly what I wanted. Highly recommend!", "date": "2024-02-20"},
    {"id": 10, "service_id": 13, "user_name": "Suresh B", "user_avatar": "https://i.pravatar.cc/150?img=10", "rating": 5, "comment": "Quick, efficient, and safe. The electrician fixed all our issues in one visit. Great value!", "date": "2024-02-08"},
]

TIME_SLOTS = [
    "09:00 AM - 10:00 AM",
    "10:00 AM - 11:00 AM",
    "11:00 AM - 12:00 PM",
    "12:00 PM - 01:00 PM",
    "02:00 PM - 03:00 PM",
    "03:00 PM - 04:00 PM",
    "04:00 PM - 05:00 PM",
    "05:00 PM - 06:00 PM",
]

CITIES = ["New Delhi", "Mumbai", "Bangalore", "Hyderabad", "Chennai", "Pune", "Kolkata", "Ahmedabad"]

# In-memory storage
users_db: Dict[int, dict] = {}
bookings_db: Dict[int, dict] = {}
user_id_counter = [1]
booking_id_counter = [1]
